### ISSUE TITLE
Epic | Random forest - address

### ISSUE THREAD

**Issue by LeoSilvaGomes** [hygia-org/hygia#14]
### Description
This **epic** was created to describe the product logic about the **random forest**

#### Keyboard smash features

| Who | When | Then |
| --- | --- | --- |
| A tech support | need to understand the keyboard smash at the data | create a value to insure the keyboard smash |
| A tech support | need to understand the keyboard smash at the data | provide a yaml to detail the columns should be analysed |

### Tasks
- #16 
- #15 

#### Word embedding features

| Who | When | Then |
| --- | --- | --- |
| A tech support | need to understand the word embedding at the data | create a value to insure the word embedding |
| A tech support | need to understand the word embedding at the data | provide a yaml to detail the columns should be analysed |

### Tasks
- #24
- #26

https://machinelearningmastery.com/what-are-word-embeddings/

#### Keyboard smash RF model

| Who | When | Then |
| --- | --- | --- |
| A tech support | need to understand the  keyboard smash at the data | create a keyboard smash indicator with random forest |
| A tech support | need to understand the keyboard smash at the data | provide a yaml to detail threshold at the insurement value created  |

### Tasks
- #18 
- #17

**Comment by RochaCarla** [comment]
# Pre processing 

- the pre-processed addresses database + keyboard smashing features for STREET_ADDRESS_1 and STREET_ADDRESS_2 concatenated
- Remove null values 

# Features extracted:


- street_address_sequence_vowels_concat
- street_address_sequence_consonants_concat
- street_address_sequence_special_characters_concat
- ksmash_number_address_concat
- char_counter_street_address_concat
- Word Embedding

# Model 
- Random forest
