### ISSUE TITLE
Generate a json to metabase from yaml

### ISSUE THREAD

**Issue by LeoSilvaGomes** [hygia-org/hygia#36]
### Description
Since we are trying to create a pipeline until the dashboard visualization, was decided to describe a json exported from **metabase** to integrate to the yaml and create a unique flow until the visualization! 

### Checklist
- [ ] Define json structure
- [ ] Describe what is required to build the json
- [ ] Create yaml structure to create json
- [ ] Define a export pipeline

**Helper:** @LeoSilvaGomes

**Comment by alvesisaque** [comment]
subir o metáfase com os Dashboards padrão, visualizações genéricas a partir do yaml, salvar e fazer o load de forma automatizada

**Comment by LeoSilvaGomes** [comment]
@francisco1code Can you add a description about why is not possible to use the metabase and what we are trying to do!

**Comment by LeoSilvaGomes** [comment]
https://github.com/orgs/hygia-org/projects/1?pane=issue&itemId=19207742

**Comment by francisco1code** [comment]
The metabase has a limitation in the free version, eventually in the case of importing the dashboard, directly affecting this functionality.

**Comment by francisco1code** [comment]
Doing some research on tools I found a [superset](https://superset.apache.org/) tool, which behaves very similarly to the metabase, but with free export and import.
