### ISSUE TITLE
requirements-dev.txt out of date

### ISSUE THREAD

**Issue by lucasgcaldas** [hygia-org/hygia#89]
### Description

Some dependencies are out of date and with conflits when I try to update the gensin from 3.8.3 to 4.3.1, because it bpemb 0.3.4 and whatlies 0.7.0 depends on gensim 3.8.3 and they are in the lastest verison. Another issue is the gensim 3.8.3 depends on numpy version that is deprecated, and is not possible add it to the project and run the project anymore.

### Checklist
- [ ] Update Cython 0.29.14 to Cython 0.29.34
- [ ] Update gensim 3.8.3 to gensim 4.3.1
- [ ] Resolve the conflicts of dependencies (Think in new libraries that has support with the main dependencies).

**Comment by AnHoff** [comment]
After further investigation, I see there's no need to update these dependencies. The errors occurred while trying to run the program, didn't they? It can be solved installing poetry (pip install poetry) and then executing "poetry install".

This worked for me, comment if it worked for you too.
